# Generated by Django 4.2.3 on 2023-07-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='User',
            new_name='user',
        ),
    ]
